version: '3.3'

services:
  analytics:
    hostname: newsfeeder
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile-dev
    volumes:
      - ./:/app
    ports:
      - "5001:80"