version: '3.5'

services:
  analytics:
    hostname: cvaden-analytics
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile-dev
    volumes:
      - ./:/app
      - ~/.config:/root/.config
    ports:
      - "8084:8084"
    dns:
      - 8.8.8.8
networks:
  default:
    name: cvaden2